### ISSUE TITLE
Problem 3 function description does not appear to match function signature

### ISSUE THREAD

**Issue by yarwelp** [cis198-2016f/homework#2]
In problem 3, the following is stated about the function:

> This function will take in a number of discs, and the names of the three pegs, and return a vector of (u8, u8) tuples. Each tuple represents one move between (source, destination).

The function signature provided is:

> ``` rust
> pub fn hanoi(num_discs: u32) -> Vec<(u8, u8)>
> ```

The part of the quoted sentence that says "and the names of the three pegs" does not appear to match this function signature. Perhaps I am misunderstanding what is meant by this?

**Comment by terryxsun** [comment]
Ooooops! I changed the function signature between last semester and this one and didn't update all of the text properly.

Thanks for pointing this out!
