### ISSUE TITLE
Is the GitHub classroom intended to be available for people who are not Penn students?

### ISSUE THREAD

**Issue by yarwelp** [cis198-2016f/homework#4]
Homework 02 includes an invitation link to join your GitHub Classroom.

In case this is intended to be available for people who are not Penn students, I will gladly join.

In case this is _not_ intended to be available outside of Penn, I suggest removing the link from the public repo and using a non-public channel for distributing the invitation to Penn students. In such case, if possible, you might also want to revoke the invitation and generate a new one.

**Comment by terryxsun** [comment]
It's public! We have a small class at Penn that falls way under the number of private repos we requested from GitHub, so anyone else who wants to use GH Classroom is welcome to join.

**Comment by yarwelp** [comment]
Excellent, thanks :)
