### ISSUE TITLE
GitHub classroom repo for hw03 is not prepopulated

### ISSUE THREAD

**Issue by yarwelp** [cis198-2016f/homework#9]
I followed the classroom link to create a private repo for hw03 like i had for hw02. The resulting repo is empty, while the description of hw03 says that the repo is supposed to be prepopulated.

My repo: https://github.com/cis198-2016f/hw03-a-better-bst-eriknstr

**Comment by terryxsun** [comment]
Dangit!

It's fixed now, and your repo should be updated.
